version: '3.7'

services:
  traefik:
    image: traefik:v2.10
    command:
      - --api.dashboard=true
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.swarmmode=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencryptresolver.acme.tlschallenge=true
      - --certificatesresolvers.letsencryptresolver.acme.email=admin@blackops7.cloud
      - --certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    networks:
      - minha_rede
    deploy:
      placement:
        constraints:
          - node.role == manager

  bot-manager:
    build: ./bot-manager
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:83e6b9e1c5aee51dc5a2947fb5f4b6af@postgres:5432/telegram_bots
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=@@@Buceta321
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    volumes:
      - ./bot-sessions:/app/sessions
      - ./bot-logs:/app/logs
      - ./bot-scripts:/app/bot-scripts
      - ./bot-configs:/app/configs
      - ./bot-exports:/app/exports
    networks:
      - minha_rede
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.bot-manager.rule=Host(`iabots.blackops7.cloud`)
        - traefik.http.routers.bot-manager.entrypoints=websecure
        - traefik.http.routers.bot-manager.tls=true
        - traefik.http.routers.bot-manager.tls.certresolver=letsencryptresolver
        - traefik.http.services.bot-manager.loadbalancer.server.port=8000

  bot-monitor:
    image: python:3.11-slim
    command: python /app/monitor.py
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:83e6b9e1c5aee51dc5a2947fb5f4b6af@postgres:5432/telegram_bots
    volumes:
      - ./bot-monitor:/app
      - ./bot-logs:/app/logs
    networks:
      - minha_rede
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  letsencrypt:

networks:
  minha_rede:
    external: true
    name: minha_rede
